// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA2jlDY8j1o0aRxEWfOMBuivWkfgA7HgI',
    appId: '1:43819193753:web:ba40eec22d616072cdaf08',
    messagingSenderId: '43819193753',
    projectId: 'maifuru-71378',
    authDomain: 'maifuru-71378.firebaseapp.com',
    storageBucket: 'maifuru-71378.firebasestorage.app',
    measurementId: 'G-N0ZE3YYEEJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2qVlJrbh8ikoswrwgVxMN6swBjBj1tEQ',
    appId: '1:43819193753:ios:6e199def8ef0d17ccdaf08',
    messagingSenderId: '43819193753',
    projectId: 'maifuru-71378',
    storageBucket: 'maifuru-71378.firebasestorage.app',
    iosBundleId: 'com.example.maifuru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA2jlDY8j1o0aRxEWfOMBuivWkfgA7HgI',
    appId: '1:43819193753:web:2f8ce0d677630324cdaf08',
    messagingSenderId: '43819193753',
    projectId: 'maifuru-71378',
    authDomain: 'maifuru-71378.firebaseapp.com',
    storageBucket: 'maifuru-71378.firebasestorage.app',
    measurementId: 'G-Y90D9JZSEJ',
  );
}
